version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      PGUSER: user
      PGPASSWORD: 1234
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: meu_banco
    command: >
      java -jar assentuando-0.0.1-SNAPSHOT.jar
      --spring.profiles.active=prd
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

